version: "2"

services:
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    # volumes:
    # TODO: requires `mkdir -p data && chmod o+rwx data`
    # - data:/opt/jboss/keycloak/standalone/data
