#!/bin/sh
set -xeu

: "${DOMAIN_SUFFIX=fr.bw-cloud-instance.org}"

domain="$(cat /var/lib/cloud/data/instance-id).$DOMAIN_SUFFIX"
hostnamectl set-hostname -- "${domain%%-*}"
hostnamectl set-hostname --pretty -- "https://$domain $(hostnamectl status --pretty)"

curl -fL https://github.com/emulation-as-a-service/cloud-init-update/raw/main/user-data | sh

apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y docker-compose

git clone https://github.com/rafaelgieschke/compose-unit
compose-unit/install

printf 'DOMAIN=%s\n' "$domain" > .env
mkdir -p -m 777 keycloak-data
compose enable --now .
